spring.application.name=AutoEscola3ESPH
server.port=8085
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/autoescola3esph}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:fiap}

api.security.token.secret=${JWT_SECRET:12345678}
app.admin.login=${ADMIN_LOGIN:admin}
app.admin.password=${ADMIN_PASSWORD:admin123}
